#!/bin/bash
# Skript väljastab tärnidest raami (õõnes ruut)

read -p "Sisesta ridade arv: " read_rows
read -p "Sisesta tärnide arv reas: " read_cols

for (( i=1; i<=read_rows; i++ ))
do
  for (( j=1; j<=read_cols; j++ ))
  do
    if [[ $i -eq 1 || $i -eq $read_rows || $j -eq 1 || $j -eq $read_cols ]]
    then
      echo -n "* "
    else
      echo -n "  "
    fi
  done
  echo " # $i. rida"
done
