#!/bin/bash
# Skript väljastab kolmnurga, kus tärnide arv igas reas = rea number

read -p "Sisesta ridade arv: " read_rows

for (( i=1; i<=read_rows; i++ ))
do
  for (( j=1; j<=i; j++ ))
  do
    echo -n "* "
  done
  echo " # $i. rida"
done
