#!/bin/bash
# Skript arvutab sisestatud täisarvu numbrite summa

read -p "Sisesta suvaline täisarv: " arv

# negatiivse arvu korral eemaldame miinusmärgi
abs_arv=${arv#-}
summa=0

while [ $abs_arv -gt 0 ]; do
  digit=$((abs_arv % 10))
  summa=$((summa + digit))
  abs_arv=$((abs_arv / 10))
done

echo "Arvu $arv numbrite summa on: $summa"
