#!/bin/bash
# Autor: Kelly Veljaots
# Kirjeldus: Kusib kasutajalt taisnime ja tervitab teda. 

echo -n "Sisesta oma ees- ja perenimi: "
read eesnimi perenimi
echo "Tere tulemast, $eesnimi $perenimi"

