#!/bin/bash
# See skript tervitab kasutajat vastavalt süsteemi kellaajale ja lisab nime.

tund=$(date +%H)
kasutaja=$(whoami)

if test $tund -ge 6 -a $tund -lt 12
then
    echo "Tere hommikust, $kasutaja!"
elif test $tund -ge 12 -a $tund -lt 18
then
    echo "Tere päevast, $kasutaja!"
elif test $tund -ge 18 -a $tund -lt 22
then
    echo "Tere õhtust, $kasutaja!"
else
    echo "Head ööd, $kasutaja!"
fi
