#!/bin/bash
#

osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"
echo -n "select your os choice [1 or 2]? "
read osch
if [ $osch -eq 1 ]; then
	echo "You Pick up Unix (Sun Os)"
else ### nested if i.e. if within if #####
	if [ $osch -eq 2 ]; then
		echo "You pick up Linux (Red Hat)"
	else
		echo "What you dont like Unix/Linux OS."
	fi
fi

#
