#!/bin/bash
# Autor: Kelly Veljaots
# Kirjeldus: Arvutab busside arvu ja ulejaanud reisijad.

echo -n "Sisesta reisijate arv: "
read reisijad
echo -n "Sisesta kohtade arv uhes bussis: "
read kohad

taisbussid=$((reisijad / kohad))
ulejaanud=$((reisijad % kohad))

echo "Taidetud busse: $taisbussid"
echo "Ulejaanud reisijad: $ulejaanud"

if [ $ulejaanud -ne 0 ]; then
	bussid=$(( taisbussid + 1 ))
else
	bussid=$taisbussid
fi

echo "Kokku on vaja $bussid bussi"
